function P = ComputeLeakage(D,P)
% define local constants
mu0 = 4e-7*pi;      % permeability of free space [H/m]
% compute leakage permeance in the outer vertical section of the winding
P.Pe_ov_int = mu0*P.lc/(2*pi*P.dwo^2)*(P.dwo*(P.ro+P.rwo)/2-2*P.ro*P.dwo+...
    P.ro^2*log(P.ro/P.rwo));
P.Pe_ov_ext = mu0*P.lc/(2*pi)*log(P.rwo/P.rco);
% compute leakage permeance in the inner vertical section of the winding
P.Pe_iv_int = mu0*P.lc/(2*pi*P.dwi^2)*(P.dwi*(P.rei+P.ra)/2-2*P.ra*P.dwi+...
    P.ra^2*log(P.rei/P.ra)+P.dwi^2*log(P.rci/P.rei));
P.Pe_iv_ext = mu0*P.lc/(2*pi)*log(P.rci/P.rei);
% compute the leakage permeance in each horizontal winding section
P.Pe_hs     = mu0/(6*pi)*(...
        P.hws((1:D.ns)+1)-P.hws(1:D.ns)+...
        ((P.hws(1:D.ns).*P.rsec((1:D.ns)+1)-...
        P.hws((1:D.ns)+1).*P.rsec(1:D.ns))./...
        (P.rsec((1:D.ns)+1)-P.rsec(1:D.ns))).*...
        log(P.rsec((1:D.ns)+1)./(P.rsec(1:D.ns))));
P.Pe_h_ext  = mu0/(2*pi)*D.dep*log(P.rco/P.rci);
% total leakage permeance
P.Plk       = P.Pe_iv_int+P.Pe_iv_ext+P.Pe_ov_int+P.Pe_ov_ext+...
        2*(sum(P.Pe_hs)+P.Pe_h_ext);
% compute leakage inductance (neglecting corners)
P.Llk = P.Plk*P.N^2;            % leakage inductance [H]
end
